"""Create tables

Revision ID: 25c4b4186cb7
Revises: 
Create Date: 2021-12-07 02:03:01.804622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c4b4186cb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=12), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('width', sa.String(length=2), nullable=False),
    sa.Column('height', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_height'), 'character', ['height'], unique=False)
    op.create_index(op.f('ix_character_name'), 'character', ['name'], unique=True)
    op.create_index(op.f('ix_character_width'), 'character', ['width'], unique=False)
    op.create_table('circle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circle_name'), 'circle', ['name'], unique=True)
    op.create_index(op.f('ix_circle_state'), 'circle', ['state'], unique=False)
    op.create_index(op.f('ix_circle_timestamp'), 'circle', ['timestamp'], unique=False)
    op.create_table('login_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=7), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_record_last_seen'), 'login_record', ['last_seen'], unique=False)
    op.create_index(op.f('ix_login_record_name'), 'login_record', ['name'], unique=False)
    op.create_index(op.f('ix_login_record_role'), 'login_record', ['role'], unique=False)
    op.create_index(op.f('ix_login_record_status'), 'login_record', ['status'], unique=False)
    op.create_index(op.f('ix_login_record_timestamp'), 'login_record', ['timestamp'], unique=False)
    op.create_index(op.f('ix_login_record_zone'), 'login_record', ['zone'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=6), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_message'), 'notification', ['message'], unique=False)
    op.create_index(op.f('ix_notification_status'), 'notification', ['status'], unique=False)
    op.create_index(op.f('ix_notification_subject'), 'notification', ['subject'], unique=False)
    op.create_index(op.f('ix_notification_timestamp'), 'notification', ['timestamp'], unique=False)
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('circle', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('dob', sa.DateTime(), nullable=False),
    sa.Column('dod', sa.DateTime(), nullable=False),
    sa.Column('yop', sa.DateTime(), nullable=True),
    sa.Column('cemetry', sa.String(length=250), nullable=True),
    sa.Column('status', sa.String(length=250), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_cemetry'), 'record', ['cemetry'], unique=False)
    op.create_index(op.f('ix_record_circle'), 'record', ['circle'], unique=False)
    op.create_index(op.f('ix_record_dob'), 'record', ['dob'], unique=False)
    op.create_index(op.f('ix_record_dod'), 'record', ['dod'], unique=False)
    op.create_index(op.f('ix_record_name'), 'record', ['name'], unique=False)
    op.create_index(op.f('ix_record_status'), 'record', ['status'], unique=False)
    op.create_index(op.f('ix_record_timestamp'), 'record', ['timestamp'], unique=False)
    op.create_index(op.f('ix_record_yop'), 'record', ['yop'], unique=False)
    op.create_index(op.f('ix_record_zone'), 'record', ['zone'], unique=False)
    op.create_table('resource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('link', sa.String(length=200), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_file_type'), 'resource', ['file_type'], unique=False)
    op.create_index(op.f('ix_resource_link'), 'resource', ['link'], unique=True)
    op.create_index(op.f('ix_resource_timestamp'), 'resource', ['timestamp'], unique=False)
    op.create_index(op.f('ix_resource_title'), 'resource', ['title'], unique=True)
    op.create_table('stencil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stencil_file_path'), 'stencil', ['file_path'], unique=True)
    op.create_index(op.f('ix_stencil_timestamp'), 'stencil', ['timestamp'], unique=False)
    op.create_index(op.f('ix_stencil_title'), 'stencil', ['title'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=14), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('circle', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_circle'), 'user', ['circle'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_timestamp'), 'user', ['timestamp'], unique=False)
    op.create_index(op.f('ix_user_zone'), 'user', ['zone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_zone'), table_name='user')
    op.drop_index(op.f('ix_user_timestamp'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_circle'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_stencil_title'), table_name='stencil')
    op.drop_index(op.f('ix_stencil_timestamp'), table_name='stencil')
    op.drop_index(op.f('ix_stencil_file_path'), table_name='stencil')
    op.drop_table('stencil')
    op.drop_index(op.f('ix_resource_title'), table_name='resource')
    op.drop_index(op.f('ix_resource_timestamp'), table_name='resource')
    op.drop_index(op.f('ix_resource_link'), table_name='resource')
    op.drop_index(op.f('ix_resource_file_type'), table_name='resource')
    op.drop_table('resource')
    op.drop_index(op.f('ix_record_zone'), table_name='record')
    op.drop_index(op.f('ix_record_yop'), table_name='record')
    op.drop_index(op.f('ix_record_timestamp'), table_name='record')
    op.drop_index(op.f('ix_record_status'), table_name='record')
    op.drop_index(op.f('ix_record_name'), table_name='record')
    op.drop_index(op.f('ix_record_dod'), table_name='record')
    op.drop_index(op.f('ix_record_dob'), table_name='record')
    op.drop_index(op.f('ix_record_circle'), table_name='record')
    op.drop_index(op.f('ix_record_cemetry'), table_name='record')
    op.drop_table('record')
    op.drop_index(op.f('ix_notification_timestamp'), table_name='notification')
    op.drop_index(op.f('ix_notification_subject'), table_name='notification')
    op.drop_index(op.f('ix_notification_status'), table_name='notification')
    op.drop_index(op.f('ix_notification_message'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_login_record_zone'), table_name='login_record')
    op.drop_index(op.f('ix_login_record_timestamp'), table_name='login_record')
    op.drop_index(op.f('ix_login_record_status'), table_name='login_record')
    op.drop_index(op.f('ix_login_record_role'), table_name='login_record')
    op.drop_index(op.f('ix_login_record_name'), table_name='login_record')
    op.drop_index(op.f('ix_login_record_last_seen'), table_name='login_record')
    op.drop_table('login_record')
    op.drop_index(op.f('ix_circle_timestamp'), table_name='circle')
    op.drop_index(op.f('ix_circle_state'), table_name='circle')
    op.drop_index(op.f('ix_circle_name'), table_name='circle')
    op.drop_table('circle')
    op.drop_index(op.f('ix_character_width'), table_name='character')
    op.drop_index(op.f('ix_character_name'), table_name='character')
    op.drop_index(op.f('ix_character_height'), table_name='character')
    op.drop_table('character')
    # ### end Alembic commands ###
