"""empty message

Revision ID: 66153d2a7cd8
Revises: 25c4b4186cb7
Create Date: 2021-12-13 21:57:13.446402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66153d2a7cd8'
down_revision = '25c4b4186cb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('file', sa.LargeBinary(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_date'), 'report', ['date'], unique=False)
    op.create_index(op.f('ix_report_timestamp'), 'report', ['timestamp'], unique=False)
    op.create_index(op.f('ix_report_title'), 'report', ['title'], unique=True)
    op.add_column('character', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_character_timestamp'), 'character', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_timestamp'), table_name='character')
    op.drop_column('character', 'timestamp')
    op.drop_index(op.f('ix_report_title'), table_name='report')
    op.drop_index(op.f('ix_report_timestamp'), table_name='report')
    op.drop_index(op.f('ix_report_date'), table_name='report')
    op.drop_table('report')
    # ### end Alembic commands ###
