"""empty message

Revision ID: 6a6d4a955560
Revises: 71819caa1584
Create Date: 2021-11-29 07:56:30.359515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6d4a955560'
down_revision = '71819caa1584'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('circle', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('dob', sa.String(length=24), nullable=False),
    sa.Column('dod', sa.String(length=24), nullable=False),
    sa.Column('stencil', sa.Text(), nullable=False),
    sa.Column('stencilPath', sa.String(length=256), nullable=False),
    sa.Column('yop', sa.String(length=4), nullable=True),
    sa.Column('cemetry', sa.String(length=250), nullable=True),
    sa.Column('status', sa.String(length=250), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_cemetry'), 'record', ['cemetry'], unique=False)
    op.create_index(op.f('ix_record_circle'), 'record', ['circle'], unique=False)
    op.create_index(op.f('ix_record_dob'), 'record', ['dob'], unique=False)
    op.create_index(op.f('ix_record_dod'), 'record', ['dod'], unique=False)
    op.create_index(op.f('ix_record_name'), 'record', ['name'], unique=False)
    op.create_index(op.f('ix_record_status'), 'record', ['status'], unique=False)
    op.create_index(op.f('ix_record_stencil'), 'record', ['stencil'], unique=True)
    op.create_index(op.f('ix_record_stencilPath'), 'record', ['stencilPath'], unique=True)
    op.create_index(op.f('ix_record_timestamp'), 'record', ['timestamp'], unique=False)
    op.create_index(op.f('ix_record_yop'), 'record', ['yop'], unique=False)
    op.create_index(op.f('ix_record_zone'), 'record', ['zone'], unique=False)
    op.drop_index('ix_user_name', table_name='user')
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.drop_index(op.f('ix_record_zone'), table_name='record')
    op.drop_index(op.f('ix_record_yop'), table_name='record')
    op.drop_index(op.f('ix_record_timestamp'), table_name='record')
    op.drop_index(op.f('ix_record_stencilPath'), table_name='record')
    op.drop_index(op.f('ix_record_stencil'), table_name='record')
    op.drop_index(op.f('ix_record_status'), table_name='record')
    op.drop_index(op.f('ix_record_name'), table_name='record')
    op.drop_index(op.f('ix_record_dod'), table_name='record')
    op.drop_index(op.f('ix_record_dob'), table_name='record')
    op.drop_index(op.f('ix_record_circle'), table_name='record')
    op.drop_index(op.f('ix_record_cemetry'), table_name='record')
    op.drop_table('record')
    # ### end Alembic commands ###
