"""User table

Revision ID: 790f0fd65017
Revises: 69237a8a0f57
Create Date: 2021-11-04 18:24:45.928463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '790f0fd65017'
down_revision = '69237a8a0f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', sa.String(length=11), nullable=True))
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###
