"""New tables

Revision ID: c2400623bd57
Revises: 790f0fd65017
Create Date: 2021-11-04 18:50:30.810198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2400623bd57'
down_revision = '790f0fd65017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recent_timestamp'), 'recent', ['timestamp'], unique=False)
    op.create_table('state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('zone', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_state_name'), 'state', ['name'], unique=True)
    op.create_index(op.f('ix_state_zone'), 'state', ['zone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_state_zone'), table_name='state')
    op.drop_index(op.f('ix_state_name'), table_name='state')
    op.drop_table('state')
    op.drop_index(op.f('ix_recent_timestamp'), table_name='recent')
    op.drop_table('recent')
    # ### end Alembic commands ###
