"""empty message

Revision ID: cc84dc4b3342
Revises: 
Create Date: 2021-11-28 17:59:29.433396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc84dc4b3342'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circle_name'), 'circle', ['name'], unique=True)
    op.create_index(op.f('ix_circle_state'), 'circle', ['state'], unique=False)
    op.create_index(op.f('ix_circle_timestamp'), 'circle', ['timestamp'], unique=False)
    op.create_table('temporary_passwords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('temp_password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('circle', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temporary_passwords_circle'), 'temporary_passwords', ['circle'], unique=False)
    op.create_index(op.f('ix_temporary_passwords_email'), 'temporary_passwords', ['email'], unique=True)
    op.create_index(op.f('ix_temporary_passwords_name'), 'temporary_passwords', ['name'], unique=True)
    op.create_index(op.f('ix_temporary_passwords_role'), 'temporary_passwords', ['role'], unique=False)
    op.create_index(op.f('ix_temporary_passwords_timestamp'), 'temporary_passwords', ['timestamp'], unique=False)
    op.create_index(op.f('ix_temporary_passwords_zone'), 'temporary_passwords', ['zone'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=14), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('circle', sa.String(length=50), nullable=False),
    sa.Column('zone', sa.String(length=20), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_circle'), 'user', ['circle'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_timestamp'), 'user', ['timestamp'], unique=False)
    op.create_index(op.f('ix_user_zone'), 'user', ['zone'], unique=False)
    op.create_table('recent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recent_timestamp'), 'recent', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recent_timestamp'), table_name='recent')
    op.drop_table('recent')
    op.drop_index(op.f('ix_user_zone'), table_name='user')
    op.drop_index(op.f('ix_user_timestamp'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_circle'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_temporary_passwords_zone'), table_name='temporary_passwords')
    op.drop_index(op.f('ix_temporary_passwords_timestamp'), table_name='temporary_passwords')
    op.drop_index(op.f('ix_temporary_passwords_role'), table_name='temporary_passwords')
    op.drop_index(op.f('ix_temporary_passwords_name'), table_name='temporary_passwords')
    op.drop_index(op.f('ix_temporary_passwords_email'), table_name='temporary_passwords')
    op.drop_index(op.f('ix_temporary_passwords_circle'), table_name='temporary_passwords')
    op.drop_table('temporary_passwords')
    op.drop_index(op.f('ix_circle_timestamp'), table_name='circle')
    op.drop_index(op.f('ix_circle_state'), table_name='circle')
    op.drop_index(op.f('ix_circle_name'), table_name='circle')
    op.drop_table('circle')
    # ### end Alembic commands ###
